### PR TITLE
Sorted methods/fields alphabetically according to CodeMaid conventions

### PR DESCRIPTION
**Pull request by igitur**

### CODE REVIEW

**Comment by igitur** [comment]
@kendallb  ?

**Comment by kendallb** [comment]
Sorry I totally forgot about this! I will fix it.

**Comment by igitur** [comment]
Just merge my PR into your repo.

**Comment by kendallb** [comment]
Ok I think I did it right :)

**Comment by igitur** [comment]
Perfect, thanks

**Pull request merged**
